version: "3.8"

services:
  srs:
    image: ossrs/srs:v6.0.166
    container_name: srs_server
    ports:
      - "1935:1935" # RTMP port
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
    command: ./objs/srs -c /usr/local/srs/conf/srs.conf
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data # Persists Caddy's state (certificates)
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - srs

volumes:
  caddy_data:
  caddy_config:
